/**
 * Markdown formatters for GitHub issue bodies, PR descriptions,
 * and summary comments.
 *
 * All functions produce GitHub-flavored markdown strings ready
 * for the `gh` CLI body parameters.
 */

// ─── Milestone Issue Body ───────────────────────────────────────────────────

export interface MilestoneData {
  id: string;
  title: string;
  vision?: string;
  successCriteria?: string[];
  slices?: Array<{ id: string; title: string; taskCount?: number }>;
}

export function formatMilestoneIssueBody(data: MilestoneData): string {
  const lines: string[] = [];

  lines.push(`# ${data.id}: ${data.title}`);
  lines.push("");

  if (data.vision) {
    lines.push("## Vision");
    lines.push(data.vision);
    lines.push("");
  }

  if (data.successCriteria?.length) {
    lines.push("## Success Criteria");
    for (const criterion of data.successCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  if (data.slices?.length) {
    lines.push("## Slices");
    lines.push("");
    lines.push("| Slice | Title | Tasks |");
    lines.push("|-------|-------|-------|");
    for (const slice of data.slices) {
      lines.push(`| ${slice.id} | ${slice.title} | ${slice.taskCount ?? "—"} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync*");

  return lines.join("\n");
}

// ─── Slice PR Body ──────────────────────────────────────────────────────────

export interface SliceData {
  id: string;
  title: string;
  goal?: string;
  mustHaves?: string[];
  demoCriterion?: string;
  tasks?: Array<{ id: string; title: string; issueNumber?: number }>;
}

export function formatSlicePRBody(data: SliceData): string {
  const lines: string[] = [];

  lines.push(`## ${data.id}: ${data.title}`);
  lines.push("");

  if (data.goal) {
    lines.push("### Goal");
    lines.push(data.goal);
    lines.push("");
  }

  if (data.mustHaves?.length) {
    lines.push("### Must-Haves");
    for (const item of data.mustHaves) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  if (data.demoCriterion) {
    lines.push("### Demo Criterion");
    lines.push(data.demoCriterion);
    lines.push("");
  }

  if (data.tasks?.length) {
    lines.push("### Tasks");
    for (const task of data.tasks) {
      const ref = task.issueNumber ? ` (#${task.issueNumber})` : "";
      lines.push(`- [ ] ${task.id}: ${task.title}${ref}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync*");

  return lines.join("\n");
}

// ─── Task Issue Body ────────────────────────────────────────────────────────

export interface TaskData {
  id: string;
  title: string;
  description?: string;
  files?: string[];
  verifyCriteria?: string[];
}

export function formatTaskIssueBody(data: TaskData): string {
  const lines: string[] = [];

  lines.push(`## ${data.id}: ${data.title}`);
  lines.push("");

  if (data.description) {
    lines.push(data.description);
    lines.push("");
  }

  if (data.files?.length) {
    lines.push("### Files");
    for (const file of data.files) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
  }

  if (data.verifyCriteria?.length) {
    lines.push("### Verification");
    for (const criterion of data.verifyCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Summary Comment ────────────────────────────────────────────────────────

export interface SummaryData {
  oneLiner?: string;
  body?: string;
  frontmatter?: Record<string, unknown>;
}

export function formatSummaryComment(data: SummaryData): string {
  const lines: string[] = [];

  if (data.oneLiner) {
    lines.push(`**Summary:** ${data.oneLiner}`);
    lines.push("");
  }

  if (data.body) {
    lines.push(data.body);
    lines.push("");
  }

  if (data.frontmatter && Object.keys(data.frontmatter).length > 0) {
    lines.push("<details>");
    lines.push("<summary>Metadata</summary>");
    lines.push("");
    lines.push("```yaml");
    for (const [key, value] of Object.entries(data.frontmatter)) {
      lines.push(`${key}: ${JSON.stringify(value)}`);
    }
    lines.push("```");
    lines.push("");
    lines.push("</details>");
  }

  return lines.join("\n");
}

// ─── Swarm Delivery Routines ───────────────────────────────────────────────

export type SwarmLaneId = "workflow" | "state" | "writer" | "uok" | "github";

export interface SwarmLaneData {
  id: SwarmLaneId;
  branch: string;
  owner?: string;
  latestCommit?: string;
  summary?: string;
  changedContracts?: string[];
  testEvidence?: string[];
  blockers?: string[];
}

export interface SwarmLanePRData {
  lane: SwarmLaneData;
  impactArea: string;
  transitionRisks: string[];
  rollbackPlan: string[];
  linkedIssue?: number;
}

export interface SwarmReleaseChecklistData {
  integrationBranch: string;
  lanes: SwarmLaneData[];
  parityReport?: string;
  rollbackDrill?: string;
  requiredChecks?: string[];
  openRisks?: string[];
}

export const SWARM_LANE_LABELS: Record<SwarmLaneId, string> = {
  workflow: "lane/workflow",
  state: "lane/state",
  writer: "lane/writer",
  uok: "lane/uok",
  github: "lane/github",
};

function checkedList(items: string[] | undefined, emptyLabel: string): string[] {
  if (!items?.length) return [`- [ ] ${emptyLabel}`];
  return items.map((item) => `- [ ] ${item}`);
}

export function formatSwarmLanePRBody(data: SwarmLanePRData): string {
  const lines: string[] = [];
  const laneLabel = SWARM_LANE_LABELS[data.lane.id];

  lines.push("## Swarm lane");
  lines.push("");
  lines.push(`**Lane:** \`${laneLabel}\``);
  lines.push(`**Branch:** \`${data.lane.branch}\``);
  if (data.lane.owner) lines.push(`**Owner:** ${data.lane.owner}`);
  if (data.lane.latestCommit) lines.push(`**Latest commit:** \`${data.lane.latestCommit}\``);
  lines.push("");

  lines.push("## Impact area");
  lines.push("");
  lines.push(data.impactArea);
  lines.push("");

  lines.push("## Changed contracts");
  lines.push(...checkedList(data.lane.changedContracts, "No shared contracts changed"));
  lines.push("");

  lines.push("## Transition risks");
  lines.push(...checkedList(data.transitionRisks, "No transition risks identified"));
  lines.push("");

  lines.push("## Rollback plan");
  lines.push(...checkedList(data.rollbackPlan, "Revert this lane PR"));
  lines.push("");

  lines.push("## Test evidence");
  lines.push(...checkedList(data.lane.testEvidence, "Test evidence pending"));
  lines.push("");

  if (data.lane.blockers?.length) {
    lines.push("## Blockers");
    for (const blocker of data.lane.blockers) lines.push(`- ${blocker}`);
    lines.push("");
  }

  if (data.linkedIssue) {
    lines.push(`Closes #${data.linkedIssue}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync swarm routines*");

  return lines.join("\n");
}

export function formatSwarmReleaseChecklistBody(data: SwarmReleaseChecklistData): string {
  const lines: string[] = [];

  lines.push(`# UOK Swarm Release Checklist`);
  lines.push("");
  lines.push(`**Integration branch:** \`${data.integrationBranch}\``);
  lines.push("");

  lines.push("## Lane summary");
  lines.push("");
  lines.push("| Lane | Branch | Owner | Commit | Status |");
  lines.push("|------|--------|-------|--------|--------|");
  for (const lane of data.lanes) {
    const owner = lane.owner ?? "";
    const commit = lane.latestCommit ? `\`${lane.latestCommit}\`` : "";
    const status = lane.blockers?.length ? "blocked" : "ready";
    lines.push(`| \`${SWARM_LANE_LABELS[lane.id]}\` | \`${lane.branch}\` | ${owner} | ${commit} | ${status} |`);
  }
  lines.push("");

  lines.push("## Required evidence");
  lines.push("- [ ] Changed contracts summarized");
  lines.push("- [ ] Transition matrix diff attached or linked");
  lines.push("- [ ] Writer sequence proof attached or linked");
  lines.push("- [ ] UOK parity report attached or linked");
  lines.push("- [ ] Rollback drill evidence attached or linked");
  lines.push("");

  if (data.requiredChecks?.length) {
    lines.push("## Required checks");
    for (const check of data.requiredChecks) lines.push(`- [ ] ${check}`);
    lines.push("");
  }

  lines.push("## Parity report");
  lines.push(data.parityReport ?? "Pending.");
  lines.push("");

  lines.push("## Rollback drill");
  lines.push(data.rollbackDrill ?? "Pending.");
  lines.push("");

  lines.push("## Open risks");
  if (data.openRisks?.length) {
    for (const risk of data.openRisks) lines.push(`- ${risk}`);
  } else {
    lines.push("None.");
  }
  lines.push("");

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync swarm routines*");

  return lines.join("\n");
}
