// Project/App: GSD-2
// File Purpose: Markdown formatters for GitHub sync issues, PR bodies, and comments.

/**
 * Markdown formatters for GitHub issue bodies, PR descriptions,
 * and summary comments.
 *
 * All functions produce GitHub-flavored markdown strings ready
 * for the `gh` CLI body parameters.
 */

import { buildPrEvidence } from "../gsd/pr-evidence.js";

// ─── Milestone Issue Body ───────────────────────────────────────────────────

export interface MilestoneData {
  id: string;
  title: string;
  vision?: string;
  successCriteria?: string[];
  slices?: Array<{ id: string; title: string; taskCount?: number }>;
}

export function formatMilestoneIssueBody(data: MilestoneData): string {
  const lines: string[] = [];

  lines.push(`# ${data.id}: ${data.title}`);
  lines.push("");

  if (data.vision) {
    lines.push("## Vision");
    lines.push(data.vision);
    lines.push("");
  }

  if (data.successCriteria?.length) {
    lines.push("## Success Criteria");
    for (const criterion of data.successCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  if (data.slices?.length) {
    lines.push("## Slices");
    lines.push("");
    lines.push("| Slice | Title | Tasks |");
    lines.push("|-------|-------|-------|");
    for (const slice of data.slices) {
      lines.push(`| ${slice.id} | ${slice.title} | ${slice.taskCount ?? "—"} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync*");

  return lines.join("\n");
}

// ─── Slice PR Body ──────────────────────────────────────────────────────────

export interface SliceData {
  id: string;
  title: string;
  goal?: string;
  mustHaves?: string[];
  demoCriterion?: string;
  tasks?: Array<{ id: string; title: string; issueNumber?: number }>;
}

export function formatSlicePRBody(data: SliceData): string {
  const summaries = [
    data.goal ? `### Goal\n${data.goal}` : "",
    data.mustHaves?.length ? `### Must-Haves\n${data.mustHaves.map((item) => `- ${item}`).join("\n")}` : "",
    data.demoCriterion ? `### Demo Criterion\n${data.demoCriterion}` : "",
    data.tasks?.length
      ? `### Tasks\n${data.tasks.map((task) => {
        const ref = task.issueNumber ? ` (#${task.issueNumber})` : "";
        return `- [ ] ${task.id}: ${task.title}${ref}`;
      }).join("\n")}`
      : "",
  ].filter(Boolean);
  const issueRefs = (data.tasks ?? [])
    .map((task) => task.issueNumber)
    .filter((issueNumber): issueNumber is number => typeof issueNumber === "number")
    .map((issueNumber) => `#${issueNumber}`);

  return buildPrEvidence({
    milestoneId: data.id,
    subjectId: data.id,
    subjectKind: "slice",
    milestoneTitle: data.title,
    changeType: "feat",
    linkedIssue: issueRefs.length > 0 ? `Related issues: ${issueRefs.join(", ")}` : undefined,
    summaries,
    testsRun: data.demoCriterion ? [`Demo criterion: ${data.demoCriterion}`] : undefined,
    rollbackNotes: ["Close this draft slice PR before merge or revert the slice squash commit from the milestone branch."],
    how: "Generated by GSD GitHub Sync from the slice plan, task issues, and branch mapping.",
  }).body;
}

// ─── Task Issue Body ────────────────────────────────────────────────────────

export interface TaskData {
  id: string;
  title: string;
  description?: string;
  files?: string[];
  verifyCriteria?: string[];
}

export function formatTaskIssueBody(data: TaskData): string {
  const lines: string[] = [];

  lines.push(`## ${data.id}: ${data.title}`);
  lines.push("");

  if (data.description) {
    lines.push(data.description);
    lines.push("");
  }

  if (data.files?.length) {
    lines.push("### Files");
    for (const file of data.files) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
  }

  if (data.verifyCriteria?.length) {
    lines.push("### Verification");
    for (const criterion of data.verifyCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Summary Comment ────────────────────────────────────────────────────────

export interface SummaryData {
  oneLiner?: string;
  body?: string;
  frontmatter?: Record<string, unknown>;
}

export function formatSummaryComment(data: SummaryData): string {
  const lines: string[] = [];

  if (data.oneLiner) {
    lines.push(`**Summary:** ${data.oneLiner}`);
    lines.push("");
  }

  if (data.body) {
    lines.push(data.body);
    lines.push("");
  }

  if (data.frontmatter && Object.keys(data.frontmatter).length > 0) {
    lines.push("<details>");
    lines.push("<summary>Metadata</summary>");
    lines.push("");
    lines.push("```yaml");
    for (const [key, value] of Object.entries(data.frontmatter)) {
      lines.push(`${key}: ${JSON.stringify(value)}`);
    }
    lines.push("```");
    lines.push("");
    lines.push("</details>");
  }

  return lines.join("\n");
}

// ─── Swarm Delivery Routines ───────────────────────────────────────────────

export type SwarmLaneId = "workflow" | "state" | "writer" | "uok" | "github";

export interface SwarmLaneData {
  id: SwarmLaneId;
  branch: string;
  owner?: string;
  latestCommit?: string;
  summary?: string;
  changedContracts?: string[];
  testEvidence?: string[];
  blockers?: string[];
}

export interface SwarmLanePRData {
  lane: SwarmLaneData;
  impactArea: string;
  transitionRisks: string[];
  rollbackPlan: string[];
  linkedIssue?: number;
}

export interface SwarmReleaseChecklistData {
  integrationBranch: string;
  lanes: SwarmLaneData[];
  parityReport?: string;
  rollbackDrill?: string;
  requiredChecks?: string[];
  openRisks?: string[];
}

export const SWARM_LANE_LABELS: Record<SwarmLaneId, string> = {
  workflow: "lane/workflow",
  state: "lane/state",
  writer: "lane/writer",
  uok: "lane/uok",
  github: "lane/github",
};

function checkedList(items: string[] | undefined, emptyLabel: string): string[] {
  if (!items?.length) return [`- [ ] ${emptyLabel}`];
  return items.map((item) => `- [ ] ${item}`);
}

export function formatSwarmLanePRBody(data: SwarmLanePRData): string {
  const laneLabel = SWARM_LANE_LABELS[data.lane.id];
  const summaries = [
    [
      "### Swarm lane",
      `**Lane:** \`${laneLabel}\``,
      `**Branch:** \`${data.lane.branch}\``,
      data.lane.owner ? `**Owner:** ${data.lane.owner}` : "",
      data.lane.latestCommit ? `**Latest commit:** \`${data.lane.latestCommit}\`` : "",
    ].filter(Boolean).join("\n"),
    `### Impact area\n${data.impactArea}`,
    `### Changed contracts\n${checkedList(data.lane.changedContracts, "No shared contracts changed").join("\n")}`,
    `### Transition risks\n${checkedList(data.transitionRisks, "No transition risks identified").join("\n")}`,
    data.lane.blockers?.length ? `### Blockers\n${data.lane.blockers.map((blocker) => `- ${blocker}`).join("\n")}` : "",
  ].filter(Boolean);

  return buildPrEvidence({
    milestoneId: laneLabel,
    subjectId: laneLabel,
    subjectKind: "workflow",
    milestoneTitle: laneLabel,
    changeType: "refactor",
    linkedIssue: data.linkedIssue ? `Closes #${data.linkedIssue}` : undefined,
    summaries,
    testsRun: data.lane.testEvidence,
    rollbackNotes: data.rollbackPlan,
    how: "Generated by GSD GitHub Sync swarm routines from lane evidence.",
  }).body;
}

export function formatSwarmReleaseChecklistBody(data: SwarmReleaseChecklistData): string {
  const lines: string[] = [];

  lines.push(`# UOK Swarm Release Checklist`);
  lines.push("");
  lines.push(`**Integration branch:** \`${data.integrationBranch}\``);
  lines.push("");

  lines.push("## Lane summary");
  lines.push("");
  lines.push("| Lane | Branch | Owner | Commit | Status |");
  lines.push("|------|--------|-------|--------|--------|");
  for (const lane of data.lanes) {
    const owner = lane.owner ?? "";
    const commit = lane.latestCommit ? `\`${lane.latestCommit}\`` : "";
    const status = lane.blockers?.length ? "blocked" : "ready";
    lines.push(`| \`${SWARM_LANE_LABELS[lane.id]}\` | \`${lane.branch}\` | ${owner} | ${commit} | ${status} |`);
  }
  lines.push("");

  lines.push("## Required evidence");
  lines.push("- [ ] Changed contracts summarized");
  lines.push("- [ ] Transition matrix diff attached or linked");
  lines.push("- [ ] Writer sequence proof attached or linked");
  lines.push("- [ ] UOK parity report attached or linked");
  lines.push("- [ ] Rollback drill evidence attached or linked");
  lines.push("");

  if (data.requiredChecks?.length) {
    lines.push("## Required checks");
    for (const check of data.requiredChecks) lines.push(`- [ ] ${check}`);
    lines.push("");
  }

  lines.push("## Parity report");
  lines.push(data.parityReport ?? "Pending.");
  lines.push("");

  lines.push("## Rollback drill");
  lines.push(data.rollbackDrill ?? "Pending.");
  lines.push("");

  lines.push("## Open risks");
  if (data.openRisks?.length) {
    for (const risk of data.openRisks) lines.push(`- ${risk}`);
  } else {
    lines.push("None.");
  }
  lines.push("");

  lines.push("---");
  lines.push("*Auto-generated by GSD GitHub Sync swarm routines*");

  return lines.join("\n");
}
